export const SET_SECTIONS = 'SET_SECTIONS';
export type SET_SECTIONS = typeof SET_SECTIONS;

export const SET_SELECTED_EDITION = 'SET_SELECTED_EDITION';
export type SET_SELECTED_EDITION = typeof SET_SELECTED_EDITION;
