export const SET_SECTIONS = 'SET_SECTIONS';
export type SET_SECTIONS = typeof SET_SECTIONS;

export const SET_SELECTED_EDITION = 'SET_SELECTED_EDITION';
export type SET_SELECTED_EDITION = typeof SET_SELECTED_EDITION;

export const SET_SEARCH_RESPONSE = 'SET_SEARCH_RESPONSE';
export type SET_SEARCH_RESPONSE = typeof SET_SEARCH_RESPONSE;
